###
## SendTransaction
POST http://localhost:8080/accounts/transaction
Content-Type: application/json

{
  "from": "1",
  "to": "1",
  "value": 100
}
###
## SendTransaction
POST http://localhost:8080/accounts/transaction
Content-Type: application/json

{
  "from": "1",
  "to": "1",
  "value": 100
}
###
## SendTransaction
POST http://localhost:8080/accounts/transaction
Content-Type: application/json

{
  "from": "1",
  "to": "1",
  "value": 100
}
###
## SendTransaction
POST http://localhost:8080/accounts/transaction
Content-Type: application/json

{
  "from": "1",
  "to": "1",
  "value": 100
}
###
## SendTransaction
POST http://localhost:8080/accounts/transaction
Content-Type: application/json

{
  "from": "1",
  "to": "1",
  "value": 100
}
###
## SendTransaction
POST http://localhost:8080/accounts/transaction
Content-Type: application/json

{
  "from": "1",
  "to": "1",
  "value": 100
}

###
## GetAllTransactions
GET http://localhost:8080/accounts/transaction