###
## CreateUser
POST http://localhost:8080/users
Content-Type: application/json

{
  "userId": "1"
}

###
## CreateAccount
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "userId": "1",
  "accountId": "1"
}

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
## LoadMoney
POST http://localhost:8080/transactions/loadMoney/1?value=100
Content-Type: application/json

###
##
GET http://localhost:8080/accounts/balance/1
Accept: application/json
