version: "3"
services:
  blockmess0:
    hostname: blockmess0
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8080:8443"
    depends_on:
      - mongo0
    environment:
      REPLICA_ID: 0
      SPRING_PROFILES_ACTIVE: blockmess,tls,mongo
      KEYSTORE_PASSWORD: password
      MONGO_HOST: mongo0
    networks:
      bft:
        ipv4_address: 172.20.0.2
  mongo0:
    image: mongo
    hostname: mongo0
    ports:
      - "27017:27017"
    networks:
      bft:
        ipv4_address: 172.20.0.12
    command: ["--bind_ip", "0.0.0.0"]
  blockmess1:
    hostname: blockmess1
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8081:8443"
    depends_on:
      - mongo1
    environment:
      REPLICA_ID: 1
      SPRING_PROFILES_ACTIVE: blockmess,tls,mongo
      KEYSTORE_PASSWORD: password
      MONGO_HOST: mongo1
    networks:
      bft:
        ipv4_address: 172.20.0.3
  mongo1:
    image: mongo
    hostname: mongo1
    ports:
      - "27018:27017"
    networks:
      bft:
        ipv4_address: 172.20.0.13
    command: ["--bind_ip", "0.0.0.0"]
  blockmess2:
    hostname: blockmess2
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8082:8443"
    depends_on:
      - mongo2
    environment:
      REPLICA_ID: 2
      SPRING_PROFILES_ACTIVE: blockmess,tls,mongo
      KEYSTORE_PASSWORD: password
      MONGO_HOST: mongo2
    networks:
      bft:
        ipv4_address: 172.20.0.4
  mongo2:
    image: mongo
    hostname: mongo2
    ports:
      - "27019:27017"
    networks:
      bft:
        ipv4_address: 172.20.0.14
    command: ["--bind_ip", "0.0.0.0"]
  blockmess3:
    hostname: blockmess3
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8083:8443"
    depends_on:
      - mongo3
    environment:
      REPLICA_ID: 3
      SPRING_PROFILES_ACTIVE: blockmess,tls,mongo
      KEYSTORE_PASSWORD: password
      MONGO_HOST: mongo3
    networks:
      bft:
        ipv4_address: 172.20.0.5
  mongo3:
    image: mongo
    hostname: mongo3
    ports:
      - "27020:27017"
    networks:
      bft:
        ipv4_address: 172.20.0.15
    command: ["--bind_ip", "0.0.0.0"]
  proxy:
    hostname: proxy
    image: sgx
    build:
      context: ../../
      dockerfile: ./server/sgx-proxy/Dockerfile
    ports:
      - "8084:8443"
    environment:
      REPLICA_ID: 4
      SPRING_PROFILES_ACTIVE: tls
      KEYSTORE_PASSWORD: password
    networks:
      bft:
        ipv4_address: 172.20.0.6
networks:
  bft:
    ipam:
      config:
        - subnet: 172.20.0.0/24
