version: "3"
services:
  bftsmart0:
    hostname: bftsmart0
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8080:8443"
    environment:
      REPLICA_ID: 0
      SPRING_PROFILES_ACTIVE: bftsmart,tls
      KEYSTORE_PASSWORD: password
    networks:
      bft:
        ipv4_address: 172.20.0.2
  bftsmart1:
    hostname: bftsmart1
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8081:8443"
    environment:
      REPLICA_ID: 1
      SPRING_PROFILES_ACTIVE: bftsmart,tls
      KEYSTORE_PASSWORD: password
    networks:
      bft:
        ipv4_address: 172.20.0.3
  bftsmart2:
    hostname: bftsmart2
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8082:8443"
    environment:
      REPLICA_ID: 2
      SPRING_PROFILES_ACTIVE: bftsmart,tls
      KEYSTORE_PASSWORD: password
    networks:
      bft:
        ipv4_address: 172.20.0.4
  bftsmart3:
    hostname: bftsmart3
    image: bft
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    ports:
      - "8083:8443"
    environment:
      REPLICA_ID: 3
      SPRING_PROFILES_ACTIVE: bftsmart,tls
      KEYSTORE_PASSWORD: password
    networks:
      bft:
        ipv4_address: 172.20.0.5
  proxy:
    hostname: proxy
    image: sgx
    build:
      context: ../../
      dockerfile: ./server/sgx-proxy/Dockerfile
    ports:
      - "8084:8443"
    environment:
      REPLICA_ID: 4
      SPRING_PROFILES_ACTIVE: tls
      KEYSTORE_PASSWORD: password
    networks:
      bft:
        ipv4_address: 172.20.0.6
networks:
  bft:
    ipam:
      config:
        - subnet: 172.20.0.0/24
