package com.csd.bftsmart.exceptions;

public enum ExceptionCode {
    SUCCESS,
    USER_EXISTS,
    USER_DOES_NOT_EXIST,
    ACCOUNT_EXISTS,
    INVALID_VALUE,
    NOT_ENOUGH_BALANCE,
    SAME_ACCOUNT,
    INVALID_USER,
    INVALID_SIGNATURE,
    ACCOUNT_DOES_NOT_EXIST,
    ACCOUNT_DOES_NOT_BELONG_TO_USER,
}
