version: "3"
services:
  bftsmart0:
    hostname: bftsmart0
    image: bft
    network_mode: host
    build:
      context: ../../
      dockerfile: ./server/rest/Dockerfile
    depends_on:
      - mongo0
    environment:
      REPLICA_ID: 0
      SPRING_PROFILES_ACTIVE: blockmess,tls,mongo
      KEYSTORE_PASSWORD: password
      MONGO_HOST: localhost
  mongo0:
    image: mongo
    hostname: mongo0
    command: ["--bind_ip", "0.0.0.0"]
    network_mode: host
    tmpfs:
      - /data/db
